In [1]:
import numpy as np

In [11]:
def w(A):
  '''
  Ordena los autovalores de la matriz A en orden ascendente
  '''
  l,V=np.linalg.eig(A)
  index=np.abs(l).argsort()
  argl=np.sort(l)
  argV=np.c_[tuple([np.c_[V[:,i]] for i in index])]

  return argl, argV

In [12]:
A=np.array([[5,-4,0],
             [-4,7,-3],
             [0,-3,5]])

In [13]:
A

array([[ 5, -4,  0],
       [-4,  7, -3],
       [ 0, -3,  5]])

In [14]:
w(A)

(array([ 0.90098049,  5.        , 11.09901951]),
 array([[-6.18673713e-01, -6.00000000e-01, -5.07191124e-01],
        [-6.33988906e-01,  1.91548674e-16,  7.73342141e-01],
        [-4.64005285e-01,  8.00000000e-01, -3.80393343e-01]]))